-- DEPRECATED: This file is superseded by team_scoped_policies.sql
--
-- The old authenticated_policies.sql used broad using(true) policies that
-- allowed any authenticated user full access to all tables regardless of
-- team membership.
--
-- Run team_scoped_policies.sql instead — it provides role-based access:
--   Owner (app_owners)  → full access everywhere
--   Team admin          → full CRUD on own team + team/member management
--   Team member         → full CRUD on own team data only
